### PR TITLE
Add tile-based algorithm for forest rendering

### PR DESCRIPTION
**Pull request by takenu**
- Reasoning: The current method of rendering LOD forests is to build a
  giant quadtree of all trees on the entire map. For very large
  forests, partitioning the whole map into nearby trees, faraway trees and
  invisible trees affects performance.
- Core additions: The classes in tiny/draw/tiledhorde.h define the tiled
  forest. Due to Renderable limitations, it is currently impossible to
  share programs across Renderables and therefore I have not yet given
  each Tile its own set of Renderable objects, but instead I copy the
  positions of instances on each tile into a large array.
- Supporting additions: I added tiny/algo/typecluster.h and
  tiny/algo/gridmap.h to support the tile management. The former,
  containing the TypeCluster and TypeClusterObject, aids memory management
  and enables logarithmic complexity lookup (similar to a quadtree). The
  latter, containing GridTile and GridMap, builds upon the TypeCluster to
  provide a tile-based structure. Finally, I created a new test executable
  to showcase and verify the new content. I also added a better heightmap,
  512hills.png, since the tasmania heightmap's high altitude does not
  result in trees near the starting location.
- Future directions: I believe it would be more elegant to allocate an
  array of instances on the GPU for each tile, rather than for the whole
  world at once. This requires fundamental changes to the Renderable,
  however, and I have chosen to postpone this for now.

CHANGES TO EXISTING CODE:
- I unified the setIcons/setMeshes functions of WorldIconHorde and StaticMeshHorde/AnimatedMeshHorde into setInstances(). I believe the interface of these classes should be identical since their role in the engine is identical, the only difference between them is the method for rendering and the exact implementation of the horde instance.
- I added a new executable to CMakeLists.txt.

### CODE REVIEW

**Comment by takenu** [comment]
Forgot to mention: in src/test_Forest.cpp I commented out all the code from src_test_TerrainFancy that I did not need anymore, for the purpose of easy comparison. The obsolete code can be removed in a future commit.

**Comment by BasFaggingerAuer** [comment]
Hmmm, this appears to have gone awry. I accepted the pull request for font rendering, which, apparently, also automatically accepted this pull request.

However, test_Forest.cpp has not been included into the repository. Any idea what went wrong?

**Comment by takenu** [comment]
My first guess would be that it's because it was included somehow because of my switching branches -  it could be that this is somehow due to some Git mechanism (unknown to me) for merging multiple pull requests at once.

But then again the pull request that I made for 'font' explicitly had the content of this pull request removed from it, so that seems strange.

Additionally, I never committed any version of the TiledHorde code where I merged the upstream repository (i.e. your version of tiny-game-engine) into my branch, so I don't see how merging could even be automatical. Since obviously the upstream repository was a dozen commits ahead of the fork.

For fixing, I will try to provide a pull request with the missing test_Forest.cpp (and anything else that could be missing) so as to avoid any serious issues due to the premature merge. Afterwards, we can discuss adjustments to TiledHorde (if desired) and include these via separate pull requests.

**Comment by takenu** [comment]
On second thought, let me add something to that. It seems like Git incorrectly -thought- that since the contents of this pull request were originally in the 'font' pull request, it should consider this one merged as well since 'font' was downstream of the TiledHorde branch.

However, I removed all TiledHorde from it, and indeed: none of the new files from TiledHorde (e.g. /tiny/algo/typecluster.h and /tiny/algo/gridmap.h) are present. Your repository is as you intended it, namely with the font code only.

Therefore I will now continue to make a separate pull request for TiledHorde to replace this one (well it should be there after all :P) and this time I will try to use a secondary branch for it. And avoid confusing Git by not properly resetting my local fork to the upstream repository before working on another fork.

**Pull request merged**
